const features = [
  [
    "🤖",
    "AI Generated Questions",
    "Get role-specific questions generated by AI.",
  ],
  [
    "📊",
    "AI Evaluation",
    "Get instant feedback on your performance and areas for improvement.",
  ],
  [
    "🛣",
    "Personalized Roadmap",
    "Get a tailored plan to guide your interview preparation.",
  ],
   [
    "🎯",
    "Interview Readiness Score",
    "Get a personalized score indicating your interview readiness.",
  ],
];

const Features = () => (
  <section
    id="features"
    className="bg-slate-950 px-5 py-20 text-white sm:px-7 lg:py-28"
  >
    <div className="mx-auto max-w-6xl">
      <div className="mx-auto max-w-2xl text-center">
        <p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-300">
          Built to help you succeed
        </p>
        <h2 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">
          Everything you need to{" "}
          <span className="font-serif font-semibold italic text-violet-300">
            show up ready.
          </span>
        </h2>
        <p className="mt-5 text-sm leading-7 text-slate-400">
          The practical tools to turn interview nerves into your competitive
          edge.
        </p>
      </div>
      <div className="mt-12 grid gap-4 md:grid-cols-3">
        {features.map(([icon, title, text]) => (
          <article
            key={title}
            className="rounded-2xl border border-white/10 bg-white/[.035] p-7 transition hover:-translate-y-1 hover:border-violet-300/35 hover:bg-violet-400/6"
          >
            <span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-400/15 text-xl text-violet-200">
              {icon}
            </span>
            <h3 className="mt-6 text-lg font-bold">{title}</h3>
            <p className="mt-3 text-sm leading-7 text-slate-400">{text}</p>
           
          </article>
        ))}
      </div>
    </div>
  </section>
);

export default Features;
